name: 'Setup Rye Action'
description: 'An action to setup Rye'
inputs:
  rye-version:
    description: 'Defaults to latest. Can be set to an explicit version to install a specific one.'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -sSf https://rye.astral.sh/get | bash
        echo "$HOME/.rye/env" >> $GITHUB_PATH
        export PATH="$HOME/.rye/env:$PATH"
        source "$HOME/.rye/env"
        rye --version
        echo $HOME
        echo $PATH
        echo $GITHUB_PATH
      shell: bash
      env:
        RYE_INSTALL_OPTION: "--yes"
        RYE_VERSION: ${{ inputs.rye-version }}
