name: 'Setup Rye Action'
description: 'An action to setup Rye'
inputs:
  rye-version:
    description: 'Defaults to latest. Can be set to an explicit version to install a specific one.'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - run: |
        ${GITHUB_ACTION_PATH}/run.sh
        rye --version
        echo $HOME
        echo $PATH
        echo $GITHUB_PATH
      shell: bash
      env:
        RYE_INSTALL_OPTION: "--yes"
        RYE_VERSION: ${{ inputs.rye-version }}
