name: 'Setup Rye Action'
description: 'An action to setup Rye'
branding:
  icon: 'package'
  color: 'black'
inputs:
  version:
    description: 'Specify a version to install, defaults to the latest version.'
    required: false
    default: 'latest'
  cache:
    description: 'Toggle caching of uv. Defaults to false.'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      if: ${{ inputs.cache }}
      with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv
    - run: ${GITHUB_ACTION_PATH}/run.sh
      shell: bash
      env:
        RYE_INSTALL_OPTION: "--yes"
        RYE_VERSION: ${{ inputs.version }}
