name: 'Setup Rye Action'
description: 'An action to setup Rye'
branding:
  icon: 'package'
  color: 'black'
inputs:
  rye-version:
    description: 'Defaults to latest. Can be set to an explicit version to install a specific one.'
    required: false
    default: 'latest'
  cache:
    description: ''
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      if: {{ inputs.cache }} == 'true'
      with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv
    - run: ${GITHUB_ACTION_PATH}/run.sh
      shell: bash
      env:
        RYE_INSTALL_OPTION: "--yes"
        RYE_VERSION: ${{ inputs.rye-version }}
