name: Rye

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rye:
    runs-on: ubuntu-latest
    steps:
      - uses: narumiruna/setup-rye-action@v1
        with:
          rye-version: latest
      - run: rye --version
